name: "Linear Release Action"
description: "Automatically labels Linear issues with release versions"
inputs:
  linearApiKey:
    description: "Linear API key"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"