name: "Linear Release Action"
description: "Automatically labels Linear issues with release versions"
inputs:
  appName:
    description: "The name of the app to release"
    required: false
  linearApiKey:
    description: "Linear API key"
    required: true
  slackToken:
    description: "Slack bot token"
    required: true
  slackChannel:
    description: "Slack channel to send release notes to"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"